stages:
  - incident-counter

variables:
  SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL}"  # Set this in GitLab CI/CD variables

daily-incident-counter:
  stage: incident-counter
  image: python:3.9-slim
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  before_script:
    - pip install uv
    - uv sync --frozen
  script:
    - uv run python -m scripts.check_incident_counter
  cache:
    key: 
      prefix: "${CI_COMMIT_REF_SLUG}"
      files:
        - pyproject.toml
        - uv.lock
    paths:
      - .venv/
  only:
    variables:
      - $SLACK_WEBHOOK_URL
